tasks:
  - init: |
      npm install
    command: |
      npx tailwindcss -i ./static/src/tailwind.css -o ./static/css/main.css --watch
  - init: |
      python -m venv _venv
      source _venv/bin/activate
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt
      python manage.py migrate
    command: |
      python manage.py runserver
ports:
  - port: 8000
    onOpen: open-browser
vscode:
  extensions:
    - ms-python.python
    - batisteo.vscode-django
